name: Crypto Alert Checker

on:
  schedule:
    # This runs the job every 15 minutes.
    - cron: '*/15 * * * *'
  # This also allows you to run it manually from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  check_alerts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js so we can run the script
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Run the alert checking script
      - name: Run Alert Checker
        env:
          # This pulls the secret webhook URL you set up in GitHub settings
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node scripts/check_alerts.js

      # Step 4: Commit the updated alert_states.json file back to the repo
      # This is the key to remembering which alerts have been sent!
      - name: Commit state file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add scripts/alert_states.json
          # Only commit and push if there are changes to the state file
          if ! git diff --quiet --exit-code scripts/alert_states.json; then
            git commit -m "Update alert states"
            git push
          else
            echo "No state changes to commit."
          fi
